
spring:
    messageSource:
        cacheSeconds: 1
    freemarker:
      template-loader-path: classpath:/web/,classpath:/static/templates/,classpath:/public/templates/,classpath:/templates/,classpath:/_templates/
      request-context-attribute: rc

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache.timeToLiveSeconds: 3600

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

authentication:
    oauth:
        clientid: jhipsterapp
        secret: mySecretOAuthSecret
# Token is valid 30 minutes
        tokenValidityInSeconds: 1800

#
# Security
#

login:
  maxTry: 3
  trialTime: 300
  banTime: 300
