
spring:
    thymeleaf:
        mode: XHTML
        cache: true
    messageSource:
        cacheSeconds: 1

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003

cache.timeToLiveSeconds: 3600

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

authentication:
    oauth:
        clientid: jhipsterapp
        secret: mySecretOAuthSecret
# Token is valid 30 minutes
        tokenValidityInSeconds: 1800

#
# Security
#

login:
  maxTry: 3
  trialTime: 300
  banTime: 300
